# Generated by Django 6.0.3 on 2026-03-24 12:56

import django_pgviews.db.migrations.operations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ncsbe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoterEventView",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "ncid",
                    models.CharField(
                        max_length=12, verbose_name="North Carolina identification number; join key"
                    ),
                ),
                ("voted_county_desc", models.CharField(blank=True, max_length=60)),
                ("election_date", models.DateField(null=True)),
                ("election_type", models.CharField(blank=True, max_length=20)),
                ("election_year", models.SmallIntegerField(null=True)),
                ("voting_method", models.CharField(blank=True, max_length=30)),
                ("voted_party_name", models.CharField(blank=True, max_length=60)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VoterView",
            fields=[
                ("county_identification_number", models.SmallIntegerField(null=True)),
                ("county_name", models.CharField(blank=True, max_length=15)),
                ("municipality_jurisdiction_name", models.CharField(blank=True, max_length=60)),
                (
                    "ncid",
                    models.CharField(
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        verbose_name="North Carolina identification number; join key",
                    ),
                ),
                ("registration_status_code", models.CharField(blank=True, max_length=2)),
                ("registered_party_code", models.CharField(blank=True, max_length=3)),
                ("gender_sex_code", models.CharField(blank=True, max_length=1)),
                ("race_code", models.CharField(blank=True, max_length=3)),
                ("ethnicity_code", models.CharField(blank=True, max_length=3)),
                ("year_of_birth", models.SmallIntegerField(null=True)),
                ("age_at_end_of_year", models.SmallIntegerField(null=True)),
                ("registration_date", models.DateField(null=True)),
                ("registration_year", models.SmallIntegerField(null=True)),
            ],
            options={
                "managed": False,
            },
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="VoterEventView",
            materialized=True,
            db_name="ncsbe_votereventview",
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="VoterView",
            materialized=True,
            db_name="ncsbe_voterview",
        ),
    ]
