# Generated by Django 6.0.3 on 2026-03-24 12:56

import django_pgviews.db.migrations.operations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ncsbe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoterEventView",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("ncid", models.CharField(max_length=12)),
                ("county_desc", models.CharField(blank=True, max_length=20)),
                ("voted_county_desc", models.CharField(blank=True, max_length=60)),
                ("election_date", models.DateField(null=True)),
                ("election_desc", models.CharField(blank=True, max_length=230)),
                ("election_type", models.CharField(blank=True, max_length=20)),
                ("election_year", models.SmallIntegerField(null=True)),
                ("voting_method", models.CharField(blank=True, max_length=30)),
                ("voted_party_cd", models.CharField(blank=True, max_length=3)),
                ("voted_party_desc", models.CharField(blank=True, max_length=60)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VoterView",
            fields=[
                ("county_id", models.SmallIntegerField(null=True)),
                ("county_desc", models.CharField(blank=True, max_length=15)),
                ("precinct_abbrv", models.CharField(blank=True, max_length=6)),
                ("precinct_desc", models.CharField(blank=True, max_length=60)),
                ("cong_dist_abbrv", models.CharField(blank=True, max_length=6)),
                ("nc_senate_abbrv", models.CharField(blank=True, max_length=6)),
                ("nc_house_abbrv", models.CharField(blank=True, max_length=6)),
                ("municipality_desc", models.CharField(blank=True, max_length=60)),
                ("ncid", models.CharField(max_length=12, primary_key=True, serialize=False)),
                ("status_cd", models.CharField(blank=True, max_length=2)),
                ("voter_status_desc", models.CharField(blank=True, max_length=25)),
                ("party_cd", models.CharField(blank=True, max_length=3)),
                ("gender_code", models.CharField(blank=True, max_length=1)),
                ("race_code", models.CharField(blank=True, max_length=3)),
                ("ethnic_code", models.CharField(blank=True, max_length=3)),
                ("birth_year", models.SmallIntegerField(null=True)),
                ("age_at_year_end", models.SmallIntegerField(null=True)),
                ("registr_dt", models.DateField(null=True)),
                ("registr_year", models.SmallIntegerField(null=True)),
            ],
            options={
                "managed": False,
            },
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="VoterEventView",
            materialized=True,
            db_name="ncsbe_votereventview",
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="VoterView",
            materialized=True,
            db_name="ncsbe_voterview",
        ),
    ]
