# Generated by Django 6.0.3 on 2026-04-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "deployment_type",
                    models.CharField(
                        choices=[
                            ("cloud-api", "Cloud API"),
                            ("cloud-managed", "Cloud Managed"),
                            ("self-hosted", "Self-Hosted"),
                        ],
                        default="cloud-api",
                        max_length=20,
                    ),
                ),
                ("provider_org", models.CharField(blank=True, max_length=100)),
                (
                    "engine",
                    models.CharField(
                        blank=True, help_text="e.g. Ollama, LM Studio", max_length=100
                    ),
                ),
                (
                    "scale",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Billions of parameters, e.g. 7 for 7B, 30 for 30B",
                        null=True,
                    ),
                ),
                (
                    "precision",
                    models.CharField(blank=True, help_text="e.g. 4bit, fp16", max_length=20),
                ),
                (
                    "size_on_disk",
                    models.FloatField(blank=True, help_text="Size on disk in GB", null=True),
                ),
                (
                    "model_uri",
                    models.URLField(
                        blank=True,
                        help_text="Reference link for the model, e.g. Hugging Face page or model card URL",
                        max_length=500,
                        verbose_name="Model URI",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToolModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sql_gen", "SQL Generation (internal)"),
                            ("voter_agent", "Voter Agent (web/CLI)"),
                        ],
                        help_text="Tool this model applies to; NULL = default for all other tools",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="agent.modelidentifier"
                    ),
                ),
            ],
        ),
    ]
