# Generated by Django 6.0.3 on 2026-04-06 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ToolModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sql_gen", "SQL Generation (internal)"),
                            ("voter_agent", "Voter Agent (web/CLI)"),
                        ],
                        help_text="Tool this model applies to; NULL = default for all other tools",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="agent.modelidentifier"
                    ),
                ),
            ],
        ),
    ]
