{{- with .Values.environmentVariables }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ncpollbook.fullname" $ }}
  labels:
    {{- include "ncpollbook.labels" $ | nindent 4 }}
stringData:
  {{- toYaml . | nindent 2 }}
type: Opaque
{{- end }}
