---
- hosts: k8s_vms
  become: yes
  tags: microk8s
  tasks:
    - name: Create directory for MicroK8s config
      ansible.builtin.file:
        path: /var/snap/microk8s/common
        state: directory
        mode: "0755"

    - name: Set MicroK8s default config
      ansible.builtin.template:
        src: templates/microk8s.default.yaml
        dest: /var/snap/microk8s/common/.microk8s.yaml
        mode: "0644"

    - name: Install MicroK8s
      snap:
        name: microk8s
        classic: yes
        channel: "{{ microk8s_channel }}"

    - name: Creates .kube directory
      ansible.builtin.file:
        path: .kube
        state: directory
      delegate_to: localhost
      become: false

    - name: microk8s kubeconfig
      run_once: true
      block:
        - name: Retrieve the client config
          ansible.builtin.command:
            cmd: microk8s config --use-loopback
          register: kube_conf

        - name: Create local kubeconfig
          ansible.builtin.copy:
            content: "{{ kube_conf.stdout | replace('127.0.0.1', ansible_facts['hostname']) }}"
            dest: ".kube/config-ncpollbook"
            mode: 0600
          delegate_to: localhost
          become: false

- hosts: k8s_api
  tags: [never, cloudflared]
  gather_facts: false
  tasks:
    # https://github.com/canonical/microk8s/issues/4864
    - name: Apply Cloudflared Helm chart
      kubernetes.core.helm:
        # context: "{{ k8s_context|mandatory }}"
        # kubeconfig: "{{ k8s_kubeconfig }}"
        chart_repo_url: https://community-charts.github.io/helm-charts
        chart_ref: cloudflared
        chart_version: "{{ k8s_cloudflare_chart_version }}"
        create_namespace: yes
        release_name: "cloudflared"
        release_namespace: "{{ k8s_cloudflare_namespace }}"
        release_values: "{{ k8s_cloudflare_release_values }}"
        wait: yes

    - name: Apply httpbin Helm chart
      kubernetes.core.helm:
        # context: "{{ k8s_context|mandatory }}"
        # kubeconfig: "{{ k8s_kubeconfig }}"
        chart_repo_url: https://matheusfm.dev/charts
        chart_ref: httpbin
        release_name: "httpbin"
        release_namespace: "{{ k8s_cloudflare_namespace }}"
        wait: yes

- hosts: k8s_api
  tags: [never, tailscale]
  gather_facts: false
  tasks:
    - name: Apply Tailscale Operator Helm chart
      kubernetes.core.helm:
        chart_repo_url: https://pkgs.tailscale.com/helmcharts
        chart_ref: tailscale-operator
        chart_version: "{{ k8s_tailscale_chart_version }}"
        create_namespace: yes
        release_name: "tailscale-operator"
        release_namespace: "{{ k8s_tailscale_namespace }}"
        release_values: "{{ k8s_tailscale_release_values }}"
        wait: yes

    - name: Apply Traefik Helm chart
      kubernetes.core.helm:
        chart_repo_url: https://traefik.github.io/charts
        chart_ref: traefik
        chart_version: "{{ k8s_traefik_chart_version }}"
        create_namespace: yes
        release_name: "traefik"
        release_namespace: "{{ k8s_traefik_namespace }}"
        release_values: "{{ k8s_traefik_release_values }}"
        wait: yes

    - name: Create Tailscale Funnel for Traefik service
      kubernetes.core.k8s:
        definition:
          # https://tailscale.com/docs/features/kubernetes-operator/how-to/cluster-ingress#exposing-a-service-to-the-public-internet-using-ingress-and-tailscale-funnel
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: tailscale-funnel-ing
            namespace: "{{ k8s_traefik_namespace }}"
            annotations:
              tailscale.com/funnel: "true"
          spec:
            defaultBackend:
              service:
                name: traefik
                port:
                  number: 80
            ingressClassName: tailscale
            tls:
              - hosts:
                  - traefik
        wait: yes

    - name: Apply whoami Helm chart
      kubernetes.core.helm:
        chart_repo_url: https://cowboysysop.github.io/charts/
        chart_ref: whoami
        create_namespace: yes
        release_name: whoami
        release_namespace: "{{ k8s_whoami_namespace }}"
        release_values: "{{ k8s_whoami_release_values }}"
        wait: yes

- hosts: k8s_api
  tags: [never, cloudflare-operator]
  gather_facts: false
  tasks:
    - name: Apply cert-manager Helm chart
      kubernetes.core.helm:
        chart_ref: oci://quay.io/jetstack/charts/cert-manager
        chart_version: v1.20.2
        create_namespace: yes
        release_name: cert-manager
        release_namespace: cert-manager
        release_values:
          crds:
            enabled: true
        wait: yes

    - name: Create cloudflare-operator-system namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: cloudflare-operator-system

    - name: Create Cloudflare API token secret
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: cloudflare-secrets
            namespace: cloudflare-operator-system
          type: Opaque
          stringData:
            CLOUDFLARE_API_TOKEN: "{{ cloudflare_api_token }}"

    - name: Create Cloudflare Operator resources
      kubernetes.core.k8s:
        definition: >
          {{
            lookup(
              'kubernetes.core.kustomize',
              dir='https://github.com/adyanth/cloudflare-operator.git/config/default?ref=v0.13.1',
            )
          }}

    - name: Create ClusterTunnel resource
      kubernetes.core.k8s:
        definition:
          apiVersion: networking.cfargotunnel.com/v1alpha2
          kind: ClusterTunnel
          metadata:
            name: cluster-tunnel
          spec:
            newTunnel:
              name: ncpollbook-operator-tunnel
            cloudflare:
              email: no-reply@example.com # FIXME
              domain: example.com # FIXME
              secret: cloudflare-secrets
              accountId: "{{ cloudflare_account_id }}"

    - name: Create ClusterTunnel resource
      kubernetes.core.k8s:
        definition:
          apiVersion: networking.cfargotunnel.com/v1alpha1
          kind: TunnelBinding
          metadata:
            name: cloudflare-tunnel
            namespace: traefik
          subjects:
            - name: traefik
              spec:
                fqdn: "foo.example.com" # FIXME
                target: http://traefik.traefik.svc.cluster.local:80
          tunnelRef:
            kind: ClusterTunnel
            name: cluster-tunnel

    - name: Apply Traefik Helm chart
      kubernetes.core.helm:
        chart_repo_url: https://traefik.github.io/charts
        chart_ref: traefik
        chart_version: "{{ k8s_traefik_chart_version }}"
        create_namespace: yes
        release_name: "traefik"
        release_namespace: "{{ k8s_traefik_namespace }}"
        release_values: "{{ k8s_traefik_release_values }}"
        wait: yes

    - name: Apply whoami Helm chart
      kubernetes.core.helm:
        chart_repo_url: https://cowboysysop.github.io/charts/
        chart_ref: whoami
        create_namespace: yes
        release_name: whoami
        release_namespace: "{{ k8s_whoami_namespace }}"
        release_values: "{{ k8s_whoami_release_values }}"
        wait: yes

- hosts: k8s_api
  tags: cloudflare-ingress
  gather_facts: false
  tasks:
    - name: Apply cloudflare-tunnel-ingress-controller Helm chart
      kubernetes.core.helm:
        chart_repo_url: https://helm.strrl.dev
        chart_ref: cloudflare-tunnel-ingress-controller
        chart_version: "{{ k8s_cloudflare_ingress_chart_version }}"
        create_namespace: yes
        release_name: "cf-tunnel-ingress"
        release_namespace: "{{ k8s_cloudflare_ingress_namespace }}"
        release_values: "{{ k8s_cloudflare_ingress_release_values }}"
        wait: yes

    - name: Apply Traefik Helm chart
      kubernetes.core.helm:
        chart_repo_url: https://traefik.github.io/charts
        chart_ref: traefik
        chart_version: "{{ k8s_traefik_chart_version }}"
        create_namespace: yes
        release_name: "traefik"
        release_namespace: "{{ k8s_traefik_namespace }}"
        release_values: "{{ k8s_traefik_release_values }}"
        wait: yes

    - name: Apply Traefik Kubernetes resources
      kubernetes.core.k8s:
        definition: "{{ lookup('template', item) | from_yaml_all | list }}"
        wait: yes
      loop:
        - templates/traefik_middlewares.yaml
        - templates/cloudflared_traefik_ingress.yaml

    - name: Apply whoami Helm chart
      kubernetes.core.helm:
        chart_repo_url: https://cowboysysop.github.io/charts/
        chart_ref: whoami
        create_namespace: yes
        release_name: whoami
        release_namespace: "{{ k8s_whoami_namespace }}"
        release_values: "{{ k8s_whoami_release_values }}"
        wait: yes

- hosts: k8s_api
  tags: [never, librechat]
  gather_facts: false
  tasks:
    - name: Create librechat namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ k8s_librechat_namespace }}"

    - name: Create LibreChat credentials secret
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: librechat-credentials-env
            namespace: "{{ k8s_librechat_namespace }}"
          type: Opaque
          stringData:
            CREDS_KEY: "{{ env_librechat_creds_key }}"
            CREDS_IV: "{{ env_librechat_creds_iv }}"
            JWT_SECRET: "{{ env_librechat_jwt_secret }}"
            JWT_REFRESH_SECRET: "{{ env_librechat_jwt_refresh_secret }}"
            MEILI_MASTER_KEY: "{{ env_librechat_meili_master_key }}"

    - name: Apply LibreChat Helm chart
      kubernetes.core.helm:
        chart_ref: oci://ghcr.io/danny-avila/librechat-chart/librechat
        chart_version: "{{ k8s_librechat_chart_version }}"
        create_namespace: yes
        release_name: librechat
        release_namespace: "{{ k8s_librechat_namespace }}"
        release_values: "{{ k8s_librechat_release_values }}"
        wait: yes

- hosts: k8s_api
  tags: [never, app]
  gather_facts: false
  tasks:
    - name: Apply ncpollbook Helm chart
      kubernetes.core.helm:
        chart_ref: "{{ playbook_dir }}/charts/ncpollbook"
        release_name: ncpollbook
        release_namespace: "{{ k8s_ncpollbook_namespace }}"
        create_namespace: yes
        release_values: "{{ k8s_ncpollbook_release_values }}"
        wait: yes
